#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

$app = require __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Loading environment
|--------------------------------------------------------------------------
|
*/
$envFile = \App\Console\EnvironmentDetector::detectEnvFile($_SERVER['argv'] ?? null);

try {
    \App\Console\EnvLoader::loadEnvFile(__DIR__, $envFile);
} catch (\Dotenv\Exception\InvalidPathException $err) {
    \printf(
        '[warning] %s in %s:%d%s',
        $err->getMessage(),
        $err->getFile(),
        $err->getLine(),
        PHP_EOL
    );
} catch (\App\Exceptions\InvalidPathException $err) {
    \printf(
        "[warning] %s, at path '%s' in %s:%d%s",
        $err->getMessage(),
        $err->getPath(),
        $err->getFile(),
        $err->getLine(),
        PHP_EOL
    );
}

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
